### ISSUE TITLE
web.ignoring() static assets

### ISSUE THREAD

**Issue by moose56** [jgrandja/messaging-sample#1]
Hi,

I am in the process of learning about Spring Security and have been playing with this project after seeing your presentation on YouTube. I have a query about cutting down the processing of static assets.

I have seen in another blog post that in a `WebSecurityConfigurerAdapter` class you can override the `configure` method like this:

```java
@Override
public void configure(WebSecurity web) {
    web.ignoring().mvcMatchers(...);
}
```

Doing this (I believe) means you can skip the whole filter chain process for specified paths. Am I correct in thinking this would be more efficient?

If so I have had a couple of issues implementing this. I created a new `WebSecurityConfigurerAdapter` and specified it as the first one to be processed:

```java
@Configuration
@Order(1)
public static class SkipSecurityConfig extends WebSecurityConfigurerAdapter {

    @Override
    public void configure(WebSecurity web) {
        web.ignoring().mvcMatchers("/assets/**", "/webjars/**");
    }
}
```
I also removed the `.antMatchers("/assets/**", "/webjars/**").permitAll()` lines from both other `WebSecurityConfigurerAdapter` classes (leaving in `.antMatchers("/").permitAll()` in `AppSecurityConfig`).

This succeeds in clearing the filter chain if I go to specific resources directly like `http://localhost:8080/assets/img/logo.png` but breaks the other `WebSecurityConfigurerAdapter` classes as they no longer seem to be picked up.

Is this a valid thing to be doing and if so how should it be implemented to ensure the 2 existing filter chains work as expected?

Thanks,

David.

**Comment by jgrandja** [comment]
@moose56 

> Doing this (I believe) means you can skip the whole filter chain process for specified paths. Am I correct in thinking this would be more efficient?

Yes, you are correct. If the request matches one of the `ignoring`, for example, `/assets/**` than the request will proceed to the resource and **not** go through the Spring Security related `Filter`'s. This is definitely more efficient.

Instead of creating `SkipSecurityConfig`, I would just configure `AppSecurityConfig` with:

```java
   @Override
    public void configure(WebSecurity web) {
        web.ignoring().mvcMatchers("/assets/**", "/webjars/**");
    }
```

I'm not sure why it wasn't working in your case having the 2 `WebSecurityConfigurerAdapter`. It's difficult to tell unless I can see a sample that reproduces the issue. Either way, `SkipSecurityConfig` is redundant.

Makes sense?

**Comment by moose56** [comment]
Thanks @jgrandja, yes that makes sense.

Typically I have just tried this change again and the app is all working as expected.

Thank you for the response, appreciated.
